RestaurantMVC/Controllers/BillsController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.DataAccess.Abstract;
using RestaurantMVC.DataAccess.Concrete;
using RestaurantMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantMVC.Controllers
{
    public class BillsController : Controller
    {
        private IBillRepository _billRepository;
        private IProductRepository _productRepository;
        private IOrderRepository _orderRepository;

        public BillsController()
        {
            _billRepository = new BillRepository();
            _productRepository = new ProductRepository();
            _orderRepository = new OrderRepository();
        }

        public IActionResult Index()
        {
            //ViewBag.bills = _billRepository.Calculate();
            return View();
        }
        public IActionResult Add()
        {
            //ViewBag.bills = _billRepository.Calculate();
            ViewBag.products = _productRepository.Getall();
            ViewBag.orders = _orderRepository.Getall();
            return View();
        }
        public IActionResult Update(int id)
        {
            ViewBag.products = _productRepository.Getall();
            ViewBag.orders = _orderRepository.Getall();
            var bill = _billRepository.GetById(id);
            if (bill==null)
            {
                RedirectToAction("Index");
            }
            ViewBag.bill = bill;
            return View();
        }

        public IActionResult Delete(int id)
        {
            _billRepository.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult Save(Bill bill)
        {
            if (bill.Id==0)
            {
                _billRepository.Add(bill);
            }
            else
            {
                _billRepository.Update(bill);
            }
            return RedirectToAction("Index");
        }
    }
}

RestaurantMVC/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.DataAccess.Abstract;
using RestaurantMVC.DataAccess.Concrete;
using RestaurantMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantMVC.Controllers
{
    public class OrdersController : Controller
    {
        private IOrderRepository _orderRepository;
        private IProductRepository _productRepository;
        private ITableRepository _tableRepository;
        private IEmployeeRepository _employeeRepository;


        public OrdersController()
        {
            _orderRepository =new OrderRepository();
            _productRepository = new ProductRepository();
            _tableRepository = new TableRepository();
            _employeeRepository=new EmployeeRepository();
        }

        public IActionResult Index()
        {
     
            ViewBag.orders =_orderRepository.GetByProduct();
            return View();
        }
        public IActionResult Kitchen()
        {

            ViewBag.orders = _orderRepository.GetByProduct();
            return View();
        }
        public IActionResult Add()
        {
            ViewBag.products = _productRepository.Getall();
            ViewBag.tables = _tableRepository.Getall();
            ViewBag.employee = _employeeRepository.Getall();
            return View();
        }
        public IActionResult Update(int id)
        {
            ViewBag.employee = _employeeRepository.Getall();
            ViewBag.products = _productRepository.Getall();
            ViewBag.tables = _tableRepository.Getall();
            var order = this._orderRepository.GetById(id);
            if (order == null)
            {
                RedirectToAction("Index");
            }
            ViewBag.order = order;
            return View();

        }
        //public IActionResult DeleteById(int id)
        //{
        //    this._orderRepository.Delete(id);
        //    return RedirectToAction("Index");
        //}
        [HttpPost]
        public IActionResult Save(Order order)
        {
            //string route = (order.Id == 0) ? "Add" : "Update";
            //if (order. == null)
            //{
            //    return RedirectToAction(route, "Please enter Name");

            //}
            //if (order.SurName == null)
            //{
            //    return RedirectToAction(route, "please enter surname");

            //}
            if (order.Id == 0)
            {
                this._orderRepository.Add(order);

            }
            else
            {
                this._orderRepository.Update(order);
            }
            return RedirectToAction("Index");
        }
   

    }
}

RestaurantMVC/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.DataAccess.Abstract;
using RestaurantMVC.DataAccess.Concrete;
using RestaurantMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantMVC.Controllers
{
    public class ProductsController : Controller
    {
        private IProductRepository _productRepository;
        private ICategoryRepository _categoryRepository;
        public ProductsController()
        {
            _productRepository = new ProductRepository();

            _categoryRepository = new CategoryRepository();
        }

        public IActionResult Index()
        {
            ViewBag.products = _productRepository.GetAllWithCategory();
            return View();
        }
        public IActionResult Add()
        {
            ViewBag.categories = this._categoryRepository.Getall();
            return View();
        }
        public IActionResult Update(int id)
        {
            ViewBag.categories = _categoryRepository.Getall();
            var product = _productRepository.GetById(id);
            if (product == null)
            {
                RedirectToAction("Index");
            }
            ViewBag.product = product;
            return View();

        }
        public IActionResult DeleteById(int id)
        {
            this._productRepository.Delete(id);
            return RedirectToAction("index");
        }

        [HttpPost]
        public IActionResult Save(Product product)
        {
            string route = (product.Id == 0) ? "Add" : "Update";
          
          
            if (product.ProductName == null)
            {
                return RedirectToAction(route ,"Please enter Name");
            }
            //if (product.Category.CategoryName == null)
            //{
            //    return RedirectToAction(route,"Please select CategoryId");
            //}
            if (product.ProductPrice == 0)
            {
                return RedirectToAction(route,  "Please enter Price");
            }
           
            if (product.Id == 0)
            {
                this._productRepository.Add(product);
            }
            else
            {
                this._productRepository.Update(product);
            }
            return RedirectToAction("Index");
        }
    }
}

RestaurantMVC/Controllers/TablesController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.DataAccess.Abstract;
using RestaurantMVC.DataAccess.Concrete;
using RestaurantMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantMVC.Controllers
{
    public class TablesController : Controller
    {
        private ITableRepository _tableRepository;
        private ISectionRepository _sectionRepository;

        public TablesController()
        {
            _tableRepository = new TableRepository();
            _sectionRepository = new SectionRepository();
        }


        public IActionResult Index()
        {
         ViewBag.tables=_tableRepository.GetTableDtos();
            return View();
        }

        public IActionResult Add()
        {
            ViewBag.sections = _sectionRepository.Getall();
            return View();
        }
        public IActionResult Save(Table table)
        {
            if (table.Id==0)
            {
                _tableRepository.Add(table);
            }
            else
            {
                _tableRepository.Update(table);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            ViewBag.sections = _sectionRepository.Getall();
            var table = _tableRepository.GetById(id);
            if (table==null)
            {
                RedirectToAction("Index");
            }
            ViewBag.table = table;
            return View();
        }

        public IActionResult DeleteById(int id)
        {
            _tableRepository.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

RestaurantMVC/Views/Shared/_Admin.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>RestaurantMvc</title>
    <link href="~/Web/dist/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="/Home/Index">Restaurant</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for Product" aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a><a class="dropdown-item" href="/Home/Privacy">Privacy</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="login.html">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav mt-3">

                        <a class="nav-link" asp-area="" asp-controller="Employees" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fa fa-user" aria-hidden="true"></i></div>
                            Employees
                        </a>

                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fa fa-table"></i></div>
                            Section & Tables
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" asp-area="" asp-controller="Sections" asp-action="Index">Sections</a><a class="nav-link" asp-controller="Tables" asp-action="Index">Tables</a></nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Categories & Products
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a><a class="nav-link" asp-controller="Products" asp-action="Index">Products</a></nav>
                        </div>

                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOrders" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fa fa-credit-card-alt" aria-hidden="true"></i></div>
                           Orders & Bills
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseOrders" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" asp-area="" asp-controller="Orders" asp-action="Index">CalculeteOrder</a><a class="nav-link" asp-controller="Orders" asp-action="Kitchen">KitchenOrder</a></nav>
                        </div>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fa fa-flag" aria-hidden="true"></i></div>
                            Z-REPORT
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                  Test
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
          @RenderBody()
              
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2019</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/js/scripts.js"></script>
</body>
</html>

RestaurantMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurantMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestaurantMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Product</a>
                            
                        </li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Bills" asp-action="Index">Bills</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Sections" asp-action="Index">Sections</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Tables" asp-action="Index">Tables</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RestaurantMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>